spring:
  # 数据源配置
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://${small-tools.mysql.master.ip}:${small-tools.mysql.master.port}/small-tools-mall${small-tools.mysql.master.url-params}
          username: ${small-tools.mysql.master.username}
          password: ${small-tools.mysql.master.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
