server:
  port: 18070

spring:
  application:
    name: nacos-provider

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos服务地址
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}

myName: nacos--dev--test # 自定义参数
