#spring:
#  servlet:
#    # 对文件上传暂时不做限制
#    multipart:
#      max-file-size: -1
#      max-request-size: -1

server:
  port: 20040
#spring:
# jackson全局处理-JSON入参及返回值Date时间
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
# fastjson全局处理-JSON入参及返回值Date时间 TODO 暂无效
#  mvc:
#    date-format: yyyy-MM-dd HH:mm:ss


# 日志收集 TODO: 修改为自己的配置
logstash:
  host: 192.168.101.88
  port: 5044
