#spring:
#  servlet:
#    # 对文件上传暂时不做限制
#    multipart:
#      max-file-size: -1
#      max-request-size: -1

server:
  port: 20040


# 日志收集 TODO: 修改为自己的配置
logstash:
  host: 192.168.101.88
  port: 5044


# Mybatis Mate 配置  可参考 => https://baomidou.com/pages/1864e1/#%E6%95%B0%E6%8D%AE%E8%8C%83%E5%9B%B4-%E6%95%B0%E6%8D%AE%E6%9D%83%E9%99%90
mybatis-mate:
  cert:
    # 请添加微信wx153666购买授权，不白嫖从我做起！ 测试证书会失效，请勿正式环境使用
    grant: thisIsTestLicense
    license: as/bsBaSVrsA9FfjC/N77ruEt2/QZDrW+MHETNuEuZBra5mlaXZU+DE1ZvF8UjzlLCpH3TFVH3WPV+Ya7Ugiz1Rx4wSh/FK6Ug9lhos7rnsNaRB/+mR30aXqtlLt4dAmLAOCT56r9mikW+t1DDJY8TVhERWMjEipbqGO9oe1fqYCegCEX8tVCpToKr5J1g1V86mNsNnEGXujnLlEw9jBTrGxAyQroD7Ns1Dhwz1K4Y188mvmRQp9t7OYrpgsC7N9CXq1s1c2GtvfItHArkqHE4oDrhaPjpbMjFWLI5/XqZDtW3D+AVcH7pTcYZn6vzFfDZEmfDFV5fQlT3Rc+GENEg==
