spring:
  security:
    user:
      name: admin
      password: 123456
  boot:
    admin:
      ui:
        title: small-tools服务状态监控

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 如果没有集成nacos则需引入客户端依赖`spring-boot-admin-starter-client`和如下配置 配置服务端地址
#spring:
# boot:
#   admin:
#     client:
#       url: http://127.0.0.1:30000