spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://${small-tools.ip}:3308/small-tools-mall?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai # MySQL在高版本需要指明是否进行SSL连接 解决则加上 &useSSL=false  ； &serverTimezone=Asia/Shanghai ：解决fastjson时差13小时问题
          name: small-tools-mall