version: '3'

# 网桥 -> 方便相互通讯
networks:
  small-tools:
    ipam:
      driver: default
      config:
        - subnet: "172.22.0.0/24"

services:
  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/mysql:5.7  # 原镜像`mysql:5.7`
    container_name: mysql5.7                                      # 容器名
    restart: unless-stopped                                       # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes:                                                      # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./mysql5.7/my.cnf:/etc/mysql/my.cnf"
      - "./mysql5.7/data:/var/lib/mysql"
      #      - "./mysql5.7/conf.d:/etc/mysql/conf.d"
      - "./mysql5.7/log/mysql/error.log:/var/log/mysql/error.log"
      - "./mysql5.7/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d" # 可执行初始化sql脚本的目录 -- tips:`/var/lib/mysql`目录下无数据的时候才会执行(即第一次启动的时候才会执行)
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: root         # 设置root用户密码
      MYSQL_DATABASE: demo              # 初始化的数据库名称
    ports:                              # 映射端口
      - "3306:3306"
    hostname: mysql
    networks:
      small-tools:
        ipv4_address: 172.22.0.10
  # ----------------------------------------------------------------------------------------------------------------------------
  nacos:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/nacos-server:2.0.3    # 原镜像`nacos/nacos-server:2.0.3`
    container_name: nacos_server                                 # 容器名为'nacos_server'
    restart: unless-stopped                                      # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    #    env_file:
    #      - ./nacos_2.0.3/env/nacos-standlone-mysql.env
    volumes:                                                     # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./nacos_2.0.3/logs:/home/nacos/logs"
      - "./nacos_2.0.3/init.d/custom.properties:/home/nacos/init.d/custom.properties"
      - "./nacos_2.0.3/conf/application.properties:/home/nacos/conf/application.properties"
      # mysql8版本以上才需要额外此配置信息 -- 无效配置，暂时性保留吧...
    #      - "./nacos_2.0.3/plugins/mysql:/home/nacos/plugins/mysql"
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      - PREFER_HOST_MODE=hostname                 # 如果支持主机名可以使用hostname,否则使用ip，默认也是ip
      - MODE=standalone                           # 单机模式启动
      - SPRING_DATASOURCE_PLATFORM=mysql          # 数据源平台 仅支持mysql或不保存empty
      - MYSQL_SERVICE_HOST=mysql                  # 注：这里不能为`127.0.0.1`或`localhost`方式！！！
      - MYSQL_SERVICE_DB_NAME=nacos_config        # 所需sql脚本位于 `nacos_xxx/nacos-mysql.sql`
      # mysql5.7 连接参数
      #      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
      # mysql8 连接参数
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
      # TODO 修改JVM调优参数
      - JVM_XMS=128m   #-Xms default :2g
      - JVM_XMX=128m   #-Xmx default :2g
      - JVM_XMN=64m    #-Xmn default :1g
      - JVM_MS=32m     #-XX:MetaspaceSize default :128m
      - JVM_MMS=32m    #-XX:MaxMetaspaceSize default :320m
      - NACOS_DEBUG=n  #是否开启远程debug，y/n，默认n
      - TOMCAT_ACCESSLOG_ENABLED=false #是否开始tomcat访问日志的记录，默认false
    ports:                              # 映射端口  (Nacos2.0版本相比1.X新增了gRPC的通信方式，因此需要增加2个端口：9848、9849)
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
      - "9555:9555"
    depends_on:
      - mysql
    networks:
      small-tools:
        ipv4_address: 172.22.0.11
    mem_limit: 1000m   # 最大使用内存
  # ----------------------------------------------------------------------------------------------------------------------------
  redis:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/redis:7.0.5                    # 镜像'redis:7.0.5'
    container_name: redis                                                             # 容器名为'redis'
    restart: unless-stopped                                                                   # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    command: redis-server /etc/redis/redis.conf --requirepass 123456 --appendonly no # 启动redis服务并添加密码为：123456,默认不开启redis-aof方式持久化配置
    #    command: redis-server --requirepass 123456 --appendonly yes # 启动redis服务并添加密码为：123456,并开启redis持久化配置
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:                            # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./redis/data:/data"
      - "./redis/config/redis.conf:/etc/redis/redis.conf"  # `redis.conf`文件内容`http://download.redis.io/redis-stable/redis.conf`
    ports:                              # 映射端口
      - "6379:6379"
    networks:
      small-tools:
        ipv4_address: 172.22.0.12
  # ----------------------------------------------------------------------------------------------------------------------------
  rabbitmq:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/rabbitmq:3.9.1-management        # 镜像`rabbitmq:3.9.1-management` 【 注：该版本包含了web控制页面 】
    container_name: rabbitmq            # 容器名为'rabbitmq'
    hostname: my-rabbit
    restart: unless-stopped                                       # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    environment: # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes: # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./rabbitmq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      #      - "./rabbitmq/config/10-default-guest-user.conf:/etc/rabbitmq/conf.d/10-default-guest-user.conf"
      #      - "./rabbitmq/data:/var/lib/rabbitmq"
      - "./rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.9.0.ez:/opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.9.0.ez"
    #      - "./rabbitmq/log:/var/log/rabbitmq"
    ports: # 映射端口
      - "5672:5672"
      - "15672:15672"
    networks:
      small-tools:
        ipv4_address: 172.22.0.13
  # ----------------------------------------------------------------------------------------------------------------------------
  sentinel:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/sentinel-dashboard:1.8.2
    container_name: sentinel                                     # 容器名为'sentinel'
    restart: unless-stopped                                      # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    environment:                                                 # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:                                                       # 映射端口
      - "8858:8858"
    networks:
      small-tools:
        ipv4_address: 172.22.0.14
  # ----------------------------------------------------------------------------------------------------------------------------
  xxl-job-admin:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/xxl-job-admin:2.3.0 # 原镜像`xuxueli/xxl-job-admin:2.3.0`
    container_name: xxl-job-admin
    restart: unless-stopped                                      # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    environment:
      # TODO 根据自己的配置修改，配置项参考源码文件：/xxl-job/xxl-job-admin/src/main/resources/application.properties
      PARAMS: "--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
               --spring.datasource.username=root
               --spring.datasource.password=root
               --server.servlet.context-path=/xxl-job-admin
               --spring.mail.host=smtp.qq.com
               --spring.mail.port=25
               --spring.mail.username=xxx@qq.com
               --spring.mail.from=xxx@qq.com
               --spring.mail.password=xxx
               --xxl.job.accessToken="
    ports:
      - "9003:8080"
    depends_on:
      - mysql
    networks:
      small-tools:
        ipv4_address: 172.22.0.15
  # ----------------------------------------------------------------------------------------------------------------------------
  seata:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/seata-server:1.5.2      # 原镜像`seataio/seata-server:1.5.2`
    container_name: seata-server                                  # 容器名为'seata-server'
    restart: unless-stopped                                       # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes: # 数据卷挂载路径设置,将本机目录映射到容器目录
      #      - "./seata/logs:/root/logs"
      - "./seata/seata-server/resources/application.yml:/seata-server/resources/application.yml"
    environment: # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      # 注册到nacos上的ip。客户端将通过该ip访问seata服务。
      # 注意公网ip和内网ip的差异。
      SEATA_IP: 172.16.16.88 # TODO 填写宿主机ip地址，不要填写容器内部ip
      # 指定seata服务启动端口
      SEATA_PORT: 8091
      #      STORE_MODE: file # 指定seata-server的事务日志存储方式, 支持db ,file,redis(Seata-Server 1.3及以上版本支持), 默认是 file
      #      SERVER_NODE: 1 # 指定seata-server节点ID, 如 1,2,3..., 默认为 根据ip生成
      #      SEATA_ENV: dev # 指定 seata-server 运行环境, 如 dev, test 等, 服务启动时会使用 registry-dev.conf 这样的配置
      # 指定配置文件位置, 如 file:/root/registry, 将会加载 /root/registry.conf 作为配置文件，
      # 如果需要同时指定 file.conf文件，需要将registry.conf的config.file.name的值改为类似file:/root/file.conf：
    #      SEATA_CONFIG_NAME: file:/root/seata-config/registry
    depends_on:
      - mysql
    ports: # 映射端口
      - "7091:7091"
      - "8091:8091"
    networks:
      small-tools:
        ipv4_address: 172.22.0.16
  # ----------------------------------------------------------------------------------------------------------------------------
  canal_admin:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/canal-admin:v1.1.5      # 原镜像`canal/canal-admin:v1.1.5`
    container_name: canal_admin               # 容器名为'canal_admin'
    restart: unless-stopped                   # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes: # 数据卷挂载路径设置,将本机目录映射到容器目录
      #      - "./canal/canal/canal-admin/conf/application.yml:/home/admin/canal-admin/conf/application.yml"
      # 如果需要jvm内存控制可放开下面注释，修改`JAVA_OPTS`参数
      #      - "./canal/canal/canal-admin/bin/startup.sh:/home/admin/canal-admin/bin/startup.sh"
      - "./canal/canal/canal-admin/logs:/home/admin/canal-admin/logs"
    environment: # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      canal.adminUser: admin
      canal.adminPasswd: 123456
      spring.datasource.address: mysql:3306
      spring.datasource.database: canal_manager
      spring.datasource.username: root
      spring.datasource.password: root
    ports:
      - "8089:8089"
    networks:
      small-tools:
        ipv4_address: 172.22.0.17
  canal_server:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/canal-server:v1.1.5      # 原镜像`canal/canal-server:v1.1.5`
    container_name: canal_server              # 容器名为'canal_server'
    restart: unless-stopped                   # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes: # 数据卷挂载路径设置,将本机目录映射到容器目录
      #      - "./canal/canal/canal-server/conf/example/instance.properties:/home/admin/canal-server/conf/example/instance.properties"
      #      - "./canal/canal/canal-server/conf/canal.properties:/home/admin/canal-server/conf/canal.properties"
      #      - "./canal/canal/canal-server/conf/canal_local.properties:/home/admin/canal-server/conf/canal_local.properties"
      - "./canal/canal/canal-server/logs:/home/admin/canal-server/logs"
    environment: # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      canal.register.ip: 172.22.0.18
      canal.admin.manager: canal_admin:8089
      canal.admin.port: 11110
      canal.admin.user: admin
      canal.admin.passwd: 6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9
    #      canal.admin.register.cluster: online
    ports:
      - "11110:11110"
      - "11111:11111"
      - "11112:11112"
    depends_on:
      - canal_admin
    links:
      - canal_admin
    networks:
      small-tools:
        ipv4_address: 172.22.0.18
  # ----------------------------------------------------------------------------------------------------------------------------
  elasticsearch:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/elasticsearch:7.9.2      # 原镜像`elasticsearch:7.9.2`
    container_name: elk_elasticsearch         # 容器名为'elk_elasticsearch'
    restart: unless-stopped                           # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes: # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./elk/elasticsearch/data:/usr/share/elasticsearch/data"
      - "./elk/elasticsearch/logs:/usr/share/elasticsearch/logs"
      - "./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    #      - "./elk/elasticsearch/config/jvm.options:/usr/share/elasticsearch/config/jvm.options"
    environment: # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      small-tools:
        ipv4_address: 172.22.0.20
  kibana:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/kibana:7.9.2       # 原镜像`kibana:7.9.2`
    container_name: elk_kibana
    restart: unless-stopped
    volumes:
      - "./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    networks:
      small-tools:
        ipv4_address: 172.22.0.21
  logstash:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/logstash:7.9.2     # 原镜像`logstash:7.9.2`
    container_name: elk_logstash
    restart: unless-stopped
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    volumes:
      - "./elk/logstash/data:/usr/share/logstash/data"
      - "./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml"
      #      - "./elk/logstash/config/logstash.conf:/usr/share/logstash/config/logstash.conf"
      - "./elk/logstash/config/small-tools:/usr/share/logstash/config/small-tools"
    #    command: logstash -f /usr/share/logstash/config/logstash.conf  # 指定logstash启动时使用的配置文件 - 指定单个文件
    command: logstash -f /usr/share/logstash/config/small-tools         # 指定logstash启动时使用的配置文件 - 指定目录夹（系统会自动读取文件夹下所有配置文件，并在内存中整合）
    ports:
      - "9600:9600"
      - "1218:1218"
      - "20010:20010"
      - "20030:20030"
      - "20040:20040"
    depends_on:
      - elasticsearch
    networks:
      small-tools:
        ipv4_address: 172.22.0.22
  # ----------------------------------------------------------------------------------------------------------------------------